@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana

object Mon
object User
object Datamon
object DBConnector
object TextUI
object JavaFX
object Controllers
object ActualMons

Datamon o-- Mon
Datamon o-- JavaFX
JavaFX o-- Controllers
Datamon o-- User
Datamon o-- TextUI
Datamon o-- DBConnector
Mon <|-- ActualMons


@enduml